# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('district', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=200, verbose_name='Email Address')),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=90, verbose_name='Address line')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
            ],
        ),
        migrations.AlterModelOptions(
            name='alderdistrict',
            options={'ordering': ('wards',)},
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='districts.PostalAddress'),
        ),
        migrations.AddField(
            model_name='person',
            name='ismemberof',
            field=models.ManyToManyField(blank=True, null=True, to='districts.Organization', verbose_name='Is member of'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='districts.PostalAddress'),
        ),
    ]
